// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksApi.Models;

namespace AirportCodes.Migrations
{
    [DbContext(typeof(ParksApiContext))]
    partial class ParksApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParksApi.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PasswordString")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PostedRating")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("ParksApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Area")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.Property<int>("Visitors")
                        .HasColumnType("int");

                    b.Property<int>("YearEstablished")
                        .HasColumnType("int");

                    b.HasKey("ParkId");

                    b.HasIndex("StateId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Area = "49,076.63 acres (198.6 km2)",
                            Description = "Covering most of Mount Desert Island and other coastal islands, Acadia features the tallest mountain on the Atlantic coast of the United States, granite peaks, ocean shoreline, woodlands, and lakes. There are freshwater, estuary, forest, and intertidal habitats.",
                            Name = "Acadia",
                            State = "Maine",
                            Visitors = 2669034,
                            YearEstablished = 1919
                        },
                        new
                        {
                            ParkId = 2,
                            Area = "242,755.94 acres (982.4 km2)",
                            Description = "The Badlands are a collection of buttes, pinnacles, spires, and mixed-grass prairies. The White River Badlands contain the largest assemblage of known late Eocene and Oligocene mammal fossils. The wildlife includes bison, bighorn sheep, black-footed ferrets, and prairie dogs.",
                            Name = "Badlands",
                            State = "South Dakota",
                            Visitors = 916932,
                            YearEstablished = 1978
                        },
                        new
                        {
                            ParkId = 3,
                            Area = "183,224.05 acres (741.5 km2)",
                            Description = "Crater Lake lies in the caldera of an ancient volcano called Mount Mazama that collapsed 7,700 years ago. The lake is the deepest in the United States and is noted for its vivid blue color and water clarity. Wizard Island and the Phantom Ship are more recent volcanic formations within the caldera. As the lake has no inlets or outlets, it is replenished only by precipitation.",
                            Name = "Crater Lake",
                            State = "Oregon",
                            Visitors = 670500,
                            YearEstablished = 1902
                        },
                        new
                        {
                            ParkId = 4,
                            Area = "64,701.22 acres (261.8 km2)",
                            Description = "The islands of the Dry Tortugas, at the westernmost end of the Florida Keys, are the site of Fort Jefferson, a Civil War-era fort that is the largest masonry structure in the Western Hemisphere. The park is home to undisturbed coral reefs and shipwrecks, and is only accessible by plane or boat.",
                            Name = "Dry Tortugas",
                            State = "Florida",
                            Visitors = 48543,
                            YearEstablished = 1992
                        },
                        new
                        {
                            ParkId = 5,
                            Area = "761,747.50 acres (3,082.7 km2)",
                            Description = "Yosemite features sheer granite cliffs, exceptionally tall waterfalls, and old-growth forests at a unique intersection of geology and hydrology. Half Dome and El Capitan rise from the park's centerpiece, the glacier-carved Yosemite Valley, and from its vertical walls drop Yosemite Falls, one of North America's tallest waterfalls at 2,425 feet (739 m) high. Three giant sequoia groves, along with a pristine wilderness in the heart of the Sierra Nevada, are home to a wide variety of rare plant and animal species",
                            Name = "Yosemite",
                            State = "California",
                            Visitors = 2268313,
                            YearEstablished = 1890
                        },
                        new
                        {
                            ParkId = 6,
                            Area = "1,508,938.57 acres (6,106.5 km2)",
                            Description = "The Everglades are the largest tropical wilderness in the United States. This mangrove and tropical rainforest ecosystem and marine estuary is home to 36 protected species, including the Florida panther, American crocodile, and West Indian manatee. Some areas have been drained and developed; restoration projects aim to restore the ecology.",
                            Name = "Everglades",
                            State = "California",
                            Visitors = 702319,
                            YearEstablished = 1934
                        },
                        new
                        {
                            ParkId = 7,
                            Area = "3,408,406.73 acres (13,793.3 km2)",
                            Description = "Death Valley is the hottest, lowest, and driest place in the United States, with daytime temperatures that have exceeded 130 °F (54 °C). The park protects Badwater Basin and its vast salt flats at the lowest elevation in North America, −282 ft (−86 m).[37] The park also protects canyons, badlands, sand dunes, mountain ranges, historic mines, springs, and more than 1,000 species of plants that grow in this geologic graben.",
                            Name = "Death Valley",
                            State = "California",
                            Visitors = 820023,
                            YearEstablished = 1890
                        });
                });

            modelBuilder.Entity("ParksApi.Models.ParkState", b =>
                {
                    b.Property<int>("ParkStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ParkId")
                        .HasColumnType("int");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("ParkStateId");

                    b.HasIndex("ParkId");

                    b.HasIndex("StateId");

                    b.ToTable("ParkState");
                });

            modelBuilder.Entity("ParksApi.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("NumberOfParks")
                        .HasColumnType("int");

                    b.HasKey("StateId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            Name = "California",
                            NumberOfParks = 2
                        },
                        new
                        {
                            StateId = 2,
                            Name = "Oregon",
                            NumberOfParks = 1
                        },
                        new
                        {
                            StateId = 3,
                            Name = "South Dakota",
                            NumberOfParks = 1
                        },
                        new
                        {
                            StateId = 4,
                            Name = "Florida",
                            NumberOfParks = 2
                        });
                });

            modelBuilder.Entity("ParksApi.Models.Park", b =>
                {
                    b.HasOne("ParksApi.Models.State", null)
                        .WithMany("Parks")
                        .HasForeignKey("StateId");
                });

            modelBuilder.Entity("ParksApi.Models.ParkState", b =>
                {
                    b.HasOne("ParksApi.Models.Park", "Park")
                        .WithMany("JoinEntities")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParksApi.Models.State", "State")
                        .WithMany("JoinEntities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Park");

                    b.Navigation("State");
                });

            modelBuilder.Entity("ParksApi.Models.Park", b =>
                {
                    b.Navigation("JoinEntities");
                });

            modelBuilder.Entity("ParksApi.Models.State", b =>
                {
                    b.Navigation("JoinEntities");

                    b.Navigation("Parks");
                });
#pragma warning restore 612, 618
        }
    }
}
